### ISSUE TITLE
Train sklearn local estimator

### ISSUE THREAD

**Issue by eveTu** [aws-samples/TensorFlow-in-SageMaker-workshop#1]
I was trying to train a sklearn local estimator using ` train_instance_type='local'`
but I got an error that there is no such instance like that.

Does the "local" train instance type available only for TensorFlow? 
`from sagemaker.tensorflow import TensorFlow
estimator = TensorFlow(base_job_name='cifar10',
                       entry_point='cifar10_keras_sm.py',
                       source_dir='training_script',
                       role=role,
                       framework_version='1.12.0',
                       py_version='py3',
                       hyperparameters={'epochs' : 1},
                       train_instance_count=1, train_instance_type='local')`

Thanks

**Comment by fernbach** [comment]
It's available for all the Framework estimators.
Make sure you're not setting the sagemaker_session variable or use `sagemaker_session=sagemaker.local.LocalSession() `
